# Site settings
title: Rivers of Words
subtitle: Poetry • Stories • Reflections
description: A collection of heartfelt poetry and stories exploring love, nature, and the human experience
author: Vivekananda Das
email: vivekanandadas@gmail.com
baseurl: "" # Change this to your repository name like "/poetry-website" if needed
url: "https://this-is-vivek.github.io" # Change username to your GitHub username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Asia/Kolkata

# Collections
collections:
  poems:
    output: true
    permalink: /:collection/:name/
  books:
    output: true
    permalink: /:collection/:name/

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "poems"
    values:
      layout: "poem"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"

# Pagination
paginate: 6
paginate_path: "/page:num/"

# SEO settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Genre configuration
genres:
  - romance
  - nature
  - philosophy
  - stories

# Social media
social:
  twitter: alexriverspoet
  instagram: rivers_poetry
  github: username # Change to your GitHub username

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Disqus comments (optional)
# disqus:
#   shortname: your-disqus-shortname
